[2024-02-12T09:06:03.745+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_DAG_V3.11.data_to_db scheduled__2024-02-12T06:51:00+00:00 [queued]>
[2024-02-12T09:06:03.805+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_DAG_V3.11.data_to_db scheduled__2024-02-12T06:51:00+00:00 [queued]>
[2024-02-12T09:06:03.809+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-12T09:06:03.835+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): data_to_db> on 2024-02-12 06:51:00+00:00
[2024-02-12T09:06:03.848+0000] {standard_task_runner.py:60} INFO - Started process 3692 to run task
[2024-02-12T09:06:03.859+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Weather_DAG_V3.11', 'data_to_db', 'scheduled__2024-02-12T06:51:00+00:00', '--job-id', '6671', '--raw', '--subdir', 'DAGS_FOLDER/Weather_dag.py', '--cfg-path', '/tmp/tmp0gs8yro7']
[2024-02-12T09:06:03.863+0000] {standard_task_runner.py:88} INFO - Job 6671: Subtask data_to_db
[2024-02-12T09:06:03.942+0000] {task_command.py:423} INFO - Running <TaskInstance: Weather_DAG_V3.11.data_to_db scheduled__2024-02-12T06:51:00+00:00 [running]> on host 06573eafe810
[2024-02-12T09:06:04.082+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Weather_DAG_V3.11' AIRFLOW_CTX_TASK_ID='data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T06:51:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T06:51:00+00:00'
[2024-02-12T09:06:04.110+0000] {postgres.py:172} INFO - Running copy expert: COPY weather_tab FROM STDIN, filename: weather.csv
[2024-02-12T09:06:04.127+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-02-12T09:06:04.145+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Weather_dag.py", line 76, in csv_db
    hook.bulk_load(tmp_file=file_name, table='weather_tab')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 194, in bulk_load
    self.copy_expert(f"COPY {table} FROM STDIN", tmp_file)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 178, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: ",0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85"
CONTEXT:  COPY weather_tab, line 1, column id: ",0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,3..."

[2024-02-12T09:06:04.155+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Weather_DAG_V3.11, task_id=data_to_db, execution_date=20240212T065100, start_date=20240212T090603, end_date=20240212T090604
[2024-02-12T09:06:04.169+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6671 for task data_to_db (invalid input syntax for type integer: ",0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85"
CONTEXT:  COPY weather_tab, line 1, column id: ",0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,3..."
; 3692)
[2024-02-12T09:06:04.205+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-12T09:06:04.223+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
