[2024-02-16T13:30:14.512+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: 1Trigger_dag.insert_value manual__2024-02-16T13:30:10.898072+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
